In [2]:
import numpy as np
import random
#from numpy.linalg import multi_dot

In [3]:
#Given the following matrices and vectors 
M = np.linspace(-8,8,9).reshape(3,3)
N = np.random.randint(-8,8, size=(3,3))
O = 2*N
v1 = np.array([1,3,5,7])
v2 = np.array([2,4,6,8])
v3 = np.array([-2,5,1,3])

The dot() function does the product of either two matrices, or two vectors.

In [4]:
N.dot(M)

array([[-16., -24., -32.],
       [-44., -48., -52.],
       [ 44.,  36.,  28.]])

In [5]:
v1.dot(v2)

100

The multidot() function returns the product of two or several matrices.

In [6]:
np.linalg.multi_dot([M,N,O])

array([[ 320., -304., -224.],
       [-112.,  -64.,  160.],
       [-544.,  176.,  544.]])

The vdot() function returns the product of two vectors. It does not perform a matrix multiplication. It should only be used for vectors. 

In [7]:
np.vdot(v1,v2)

100

The inner() function returns the inner product of two arrays.

In [8]:
np.inner(v3,v1)

39

The mamut() function returns the product of two matrices.

In [9]:
np.matmul(M, N)

array([[-32.,  68.,  24.],
       [ -8.,  -4.,  12.],
       [ 16., -76.,   0.]])

The linalg.matrix_power(M,n) raises the square matrix M to the power of n.

In [10]:
np.linalg.matrix_power(M,3)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

The linalg.eig(O) returns both the eigenvalues and eigenvectors of the matrix O.

In [14]:
eig_vals, eig_vects = np.linalg.eig(O)

In [15]:
eig_vals

array([13.69630739+0.j        , -2.84815369+2.43030811j,
       -2.84815369-2.43030811j])

In [16]:
eig_vects

array([[-0.02610595+0.j        , -0.7077205 +0.j        ,
        -0.7077205 -0.j        ],
       [-0.42156885+0.j        , -0.30135478+0.1823508j ,
        -0.30135478-0.1823508j ],
       [ 0.90642053+0.j        , -0.60893512+0.06529311j,
        -0.60893512-0.06529311j]])

The linalg.eigh(N) returns both the eigenvalues and the eigenvectors of a complex Hermitian matrix or a real symmetric matrix N.

In [17]:
eigh_vals, eigh_vectors = np.linalg.eigh(N)

In [18]:
eigh_vals 

array([-6.45217996,  0.76821264,  9.68396732])

In [19]:
eigh_vectors

array([[-0.30070223,  0.83557875, -0.45976767],
       [ 0.8508363 ,  0.01723628, -0.52514808],
       [ 0.4308779 ,  0.54910022,  0.71612372]])

The linalg.det(N) returns the determinant of the matrix N.

In [20]:
np.linalg.det(N)

23.999999999999993

The linalg.inv(N) returns the invers of the matrix N.

In [21]:
np.linalg.inv(N)

array([[-1.33333333,  1.16666667,  0.5       ],
       [-0.33333333,  0.16666667, -0.        ],
       [-1.16666667,  0.83333333,  0.5       ]])