In [ ]:
import numpy as np
import random 

In [8]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Particular matrices. Identity matrix. Zeros matrix. Ones matrix. Diagonal matrix

In [12]:
#Identity matrix
N = np.eye(5,3)
N

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#Zeros matrix
O = np.zeros((4,8))
O

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
#Ones matrix
P = np.ones((3,4))
P

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#Diaagonal matrix
L = np.diag((1,2,3,4,5))
L

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [23]:
#Random Matrix
B = np.random.randint(-2,3, size=(2,2))
B

array([[-2,  2],
       [ 1,  0]])