Importing libraries 

In [1]:
import numpy as np
from IPython.display import display,Latex
import sympy as sy

Given the following system of linear equations (I)
4x + 3y + 2z = 25
-2x + 2y + 3z = -10
3x - 5y + 2z = -4

Solve Linear Equation Using Inverse Method

In [4]:
#Let
M = np.array([[4,3,2], [-2,2,3], [3, -5, 2]]) #Is the coefficients matrix 
M

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [6]:
#,
K = np.array([[25],[-10],[-4]]) #The column matrix
K

array([[ 25],
       [-10],
       [ -4]])

In [8]:
#and
V = np.array([['x'],['y'],['z']])
V

array([['x'],
       ['y'],
       ['z']], dtype='<U1')

Equation can be written as 

$M * V = K\\
so,\\
V = Invese of M times K$



Solve linear equation using inverse method

In [9]:
V = np.linalg.inv(M).dot(K)
V

array([[ 5.],
       [ 3.],
       [-2.]])

#That is, 
$x=5\\
y=3\\
z=-2$

Solve Linear Equation Using Reduced Row Echelon Form

In [10]:
from sympy import *
#The augmented Matrix is
A = Matrix([[4,3,2,25],[-2,2,3,-10], [3,-5,2,-4]])

In [11]:
A

Matrix([
[ 4,  3, 2,  25],
[-2,  2, 3, -10],
[ 3, -5, 2,  -4]])

In [12]:
M

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [13]:
K

array([[ 25],
       [-10],
       [ -4]])

In [16]:
Matrix([[4,3,2,25],[-2,2,3,-10], [3,-5,2,-4]]).rref(pivots=False)

Matrix([
[1, 0, 0,  5],
[0, 1, 0,  3],
[0, 0, 1, -2]])

#Hence
$x=5\\
y=3\\
z=-2$

Solve Linear Equation Using la.solve{} method

In [18]:
Sol = np.linalg.solve(M,K)
Sol

array([[ 5.],
       [ 3.],
       [-2.]])