# Using matrix algebra in python

In [3]:
import numpy as np
import random

### Multiplying matrices 

In [4]:
L = np.linspace(-8,8,9)
L

array([-8., -6., -4., -2.,  0.,  2.,  4.,  6.,  8.])

In [5]:
M = L.reshape(3,3)
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [6]:
N = np.random.randint(-8,8, size=(3,3))
N

array([[-1,  0,  6],
       [-6, -1, -7],
       [-6,  6, -3]])

In [7]:
# Using matmul method

In [8]:
np.matmul(M,N)

array([[ 68., -18.,   6.],
       [-10.,  12., -18.],
       [-88.,  42., -42.]])

### Using the dot method 

In [9]:
M.dot(N)

array([[ 68., -18.,   6.],
       [-10.,  12., -18.],
       [-88.,  42., -42.]])

In [10]:
###Using the @
M@N

array([[ 68., -18.,   6.],
       [-10.,  12., -18.],
       [-88.,  42., -42.]])

In [12]:
A = np.array([[1,2,3],[4,5,6]])

In [15]:
B = np.array([[7,2,-3],[0,1,6]])

In [20]:
A


array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
B

array([[ 7,  2, -3],
       [ 0,  1,  6]])

In [22]:
A.dot(B.T)

array([[ 2, 20],
       [20, 41]])